# Generated by Django 4.2 on 2023-11-01 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('EnterpriseAnnual', 'enta'), ('PremiumAnnual', 'prema'), ('ProfessionalAnnual', 'proa'), ('EnterpriseMonthly', 'entm'), ('PremiumMonthly', 'premm'), ('ProfessionalMonthly', 'prom'), ('EnterpriseQuarterly', 'entq'), ('PremiumQuarterly', 'premq'), ('ProfessionalQuarterly', 'proq'), ('Free', 'free')], default='Free', max_length=30)),
                ('membership_name', models.CharField(choices=[('Enterprise', 'ent'), ('Premium', 'prem'), ('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30)),
                ('price', models.FloatField(default=10)),
                ('monthly_price', models.FloatField(default=10, null=True)),
                ('stripe_plan_id', models.CharField(max_length=40)),
                ('allowed_question', models.IntegerField()),
                ('allowed_words', models.IntegerField(null=True)),
                ('allowed_tests', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('used_tokens', models.IntegerField(default=0, null=True)),
                ('requests', models.IntegerField(default=0, null=True)),
                ('last_request_time', models.IntegerField(default=0, null=True)),
                ('cost', models.FloatField(default=0, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.usermembership')),
            ],
        ),
    ]
