# Generated by Django 4.2 on 2023-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_membership_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_name',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Premium', 'prem'), ('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('EnterpriseAnnual', 'ent'), ('PremiumAnnual', 'prem'), ('ProfessionalAnnual', 'pro'), ('EnterpriseMonthly', 'ent'), ('PremiumMonthly', 'prem'), ('ProfessionalMonthly', 'pro'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
