# Generated by Django 4.2 on 2023-08-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_membership_membership_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('EnterpriseAnnual', 'enta'), ('PremiumAnnual', 'prema'), ('ProfessionalAnnual', 'proa'), ('EnterpriseMonthly', 'entm'), ('PremiumMonthly', 'premm'), ('ProfessionalMonthly', 'prom'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
