# Generated by Django 4.2 on 2023-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('EnterpriseAnnual', 'enta'), ('PremiumAnnual', 'prema'), ('ProfessionalAnnual', 'proa'), ('EnterpriseMonthly', 'entm'), ('PremiumMonthly', 'premm'), ('ProfessionalMonthly', 'prom'), ('EnterpriseQuarterly', 'entq'), ('PremiumQuarterly', 'premq'), ('ProfessionalQuarterly', 'proq'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
