# Generated by Django 4.2 on 2023-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_name',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Premium', 'prem'), ('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30, null=True),
        ),
    ]
