# Generated by Django 4.2 on 2023-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_membership_membership_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_name',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Premium', 'prem'), ('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
