# Generated by Django 4.2 on 2023-09-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_membership_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='used_tokens',
            field=models.IntegerField(null=True),
        ),
    ]
