# Generated by Django 4.2 on 2023-09-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_usermembership_used_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
