# Generated by Django 4.2 on 2023-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_usermembership_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='used_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
