# Generated by Django 4.2 on 2023-07-30 00:39

import createtests.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', createtests.models.StrippedCharField(max_length=266)),
                ('subtitle', createtests.models.StrippedCharField(max_length=266)),
                ('institution', createtests.models.StrippedCharField(max_length=266)),
                ('add_header_info', createtests.models.StrippedTextField(max_length=1500)),
                ('grades', createtests.models.StrippedJSONField(null=True)),
                ('question_types', createtests.models.StrippedJSONField(null=True)),
                ('questions', createtests.models.StrippedJSONField(null=True)),
                ('footer', createtests.models.StrippedTextField(max_length=1500, null=True)),
                ('notes', createtests.models.StrippedTextField(max_length=266, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
