# Generated by Django 4.2 on 2023-10-21 21:34

import createtests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', createtests.models.StrippedCharField(max_length=266)),
                ('body', createtests.models.StrippedTextField(max_length=3000)),
                ('your_field', models.IntegerField()),
            ],
        ),
    ]
