# Generated by Django 4.2 on 2023-10-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createtests', '0002_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
