"""
Django settings for practicetests project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k+)h#sjch5*75o4n4!hhh482t%$)%m3mx$62c!e=545x30@-3d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'createtests',
    'mytests',
    'homepage',
    'payment',
    'captcha'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'practicetests.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'practicetests.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "djangoappdb",
        'USER': "postgres",
        'PASSWORD': "Postgres123!",
        'HOST': "localhost",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'practicetests/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Stripe keys
if DEBUG:
    STRIPE_PUBLISHABLE_KEY = "pk_test_51MZ5ggEIvcSmcyn9LuHa58613iOsS5uuQsG0VRwDgfjBBQpjVCw7uomEy9y6MMDaRtJ1LC2UwBlDxy9I0lXSh6WP00RpILQewy"
    STRIPE_SECRET_KEY = "sk_test_51MZ5ggEIvcSmcyn9g9XQHOMrydvU4IYJB6punDJWwC3HjKNctvy6TzHOoKdqdgrlphM1rtKkyO1fv632mC0Sm5ak00a2lQ8CPX"
else:
    STRIPE_PUBLISHABLE_KEY = "pk_live_51MZ5ggEIvcSmcyn9W26qP1FWzOnp3fIADWpzkim1WGfpuybGKJVmDW0wWyiZo95xF4cM8v5ZInHEk6HqzaRE9A7700GzpO1Q0f"
    STRIPE_SECRET_KEY = "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"

# Captcha keys
RECAPTCHA_PUBLIC_KEY = "6LcIX_EnAAAAAHpV9vPofXRc8CzSfwKdWdp2lJY2"
RECAPTCHA_PRIVATE_KEY = "6LcIX_EnAAAAAPAt1WRXgN8b9aWlClwgEhBadtJS"

# OpenAI Keys
OPENAI_API_KEY = "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"
